--- # Playbook para Test Toolbox TVE
- hosts: localhost
  gather_facts: yes
  become: yes
  tasks:
    - name: Instalo los paquetes requeridos
      yum:
        name: 
          - http://nginx.org/packages/centos/7/noarch/RPMS/nginx-release-centos-7-0.el7.ngx.noarch.rpm
          - nginx
          - php-fpm
          - mariadb-server
          - mariadb
          - git
        state: present
    - name: Creo el directorio raiz y copio archivo
      file:
        path: /var/www/html
        state: directory
      copy:
        src: /usr/share/nginx/html/index.html
        dest: /var/www/html/
    - name: Tunning de servicios
      service:
        name: php-fpm
        state: started
        name: php-fpm.service
        enabled: yes
        name: nginx.service
        enabled: yes
        name: nginx
        state: restarted