--- # Playbook para Test Toolbox TVE
- hosts: localhost
  gather_facts: no
  become: yes
  tasks:
    - name: Instalo los paquetes requeridos
      yum:
        name: 
          - http://nginx.org/packages/centos/7/noarch/RPMS/nginx-release-centos-7-0.el7.ngx.noarch.rpm
          - nginx
          - php-fpm
          - mariadb-server
          - mariadb
        state: present
    - name: Creo el directorio raiz y copio archivo
      file:
        path: /var/www/html
        state: directory
      copy:
        src: /usr/share/nginx/html/index.html
        dest: /var/www/html/
      copy:
        content: |
         server {
           listen 80 default_server;
           listen [::]:80 default_server ipv6only=on;
           
           root /var/www/html;
           index index.php index.html index.htm;
           
           server_name localhost;
           
           location / {
               try_files $uri $uri/ =404;
            }
            
            error_page 404 /404.html;
            error_page 500 502 503 504 /50x.html;
            location = /50x.html {
                root /usr/share/nginx/html;
            }
            
            location ~ \.php$ {
                try_files $uri =404;
                fastcgi_split_path_info ^(.+\.php)(/.+)$;
                fastcgi_pass unix:/var/run/php-fpm/php-fpm.sock;

                fastcgi_index index.php;
                fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
                include fastcgi_params;
            }
         }
         dest: /etc/nginx/conf.d/default.conf
      copy:
        content: |
          <?php
          phpinfo();
          ?>
- name: Tunning de configuracion
    shell: "sed -i -e "s/;cgi.fix_pathinfo=1/cgi.fix_pathinfo=0/" /etc/php.ini"
    shell: "sed -i -e "s|listen = 127.0.0.1:9000|listen = /var/run/php-fpm/php-fpm.sock|" /etc/php-fpm.d/www.conf"
    
- name: Tunning de servicios
    service:
      name: php-fpm
      state: started
    service:
      name: php-fpm.service
      enabled: yes
    service:
      name: nginx.service
      enabled: yes
    service:
      name: nginx
      state: restarted